#' Show information about an OSM file
#'
#' @description
#' This is a wrapper for [osmium fileinfo](https://docs.osmcode.org/osmium/latest/osmium-fileinfo.html).
#' Returns OSM file & header info in three possible formats:
#' - \code{"text"}: the original plain‐text dump
#' - \code{"json"}: the raw JSON string emitted by \code{--json}
#' - \code{"list"}: the JSON parsed to an R list via \code{RcppSimdJson::fparse()}
#'
#' @param input_path    String. Path to the OSM file.
#' @param extended      A logical(1). Read the entire file (not just header)? Defaults to `FALSE`. Reading extended info may be slow, as it reads the entire file. This is also required if the file does not have a bounding box in the header, and you need to calculate it from the data. Specifically, to get or calculate the bounding box, you need can use the [osm_get_bbox] function.
#' @param get           String or NULL. If non‐NULL, return only this one variable.
#' @param crc           A logical. Calculate CRC32? Defaults to `FALSE`.
#' @param object_type   Character vector or NULL. Only for \code{extended = TRUE}. Defaults to \code{NULL}.
#' @param output        One of \code{"text"}, \code{"json"}, \code{"list"}.
#'                      Defaults to \code{"text"}.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by the function call to the screen.
#'   Defaults to `FALSE`.
#' @param echo A logical. Whether to print the standard output and error generated by the Osmium call to the screen.
#'   Defaults to `TRUE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the Osmium call is being executed.
#'   Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the running command. Defaults to `FALSE`.
#' @param progress A logical. Whether to display a progress bar while running
#'   the command. Defaults to `FALSE`.
#'
#' @return Depending on \code{output}:
#' * \code{"text"}: character scalar (the plain‐text dump).
#' * \code{"json"}: character scalar (the JSON string).
#' * \code{"list"}: an R list parsed via \code{RcppSimdJson::fparse()}.
#'
#' @importFrom RcppSimdJson fparse
#'
#' @examplesIf identical(tolower(Sys.getenv("NOT_CRAN")), "true")
#' pbf <- system.file("extdata/cur.osm.pbf", package = "rosmium")
#'
#' # 1. plain-text (default)
#' txt <- osm_file_info(pbf)
#' cat(substr(txt, 1, 200), "...", "\n")
#'
#' # 2. raw JSON
#' j <- osm_file_info(pbf, output = "json")
#' cat(substr(j, 1, 200), "...", "\n")
#
#' # 3. parsed list
#' lst <- osm_file_info(pbf, output = "list")
#' str(lst[c("file","header")])
#'
#'
#' @export
osm_file_info <- function(
    input_path,
    extended = FALSE,
    get = NULL,
    crc = FALSE,
    object_type = NULL,
    output = c("text", "json", "list"),
    echo_cmd = FALSE,
    echo = FALSE,
    spinner = TRUE,
    verbose = FALSE,
    progress = FALSE
) {
    assert_osmium_is_installed()
    checkmate::assert_file_exists(input_path)
    checkmate::assert_logical(extended, any.missing = FALSE, len = 1)
    checkmate::assert_logical(crc, any.missing = FALSE, len = 1)
    checkmate::assert_logical(echo_cmd, any.missing = FALSE, len = 1)
    checkmate::assert_logical(echo, any.missing = FALSE, len = 1)
    checkmate::assert_logical(spinner, any.missing = FALSE, len = 1)
    checkmate::assert_logical(verbose, any.missing = FALSE, len = 1)
    checkmate::assert_logical(progress, any.missing = FALSE, len = 1)
    output <- match.arg(output)

    if (!is.null(get)) {
        checkmate::assert_string(get)
        if (output == "list") {
            warning("`get` overrides `output = 'list'`; returning plain text")
            output <- "text"
        }
    }
    if (!is.null(object_type)) {
        checkmate::assert_subset(
            object_type,
            choices = c("node", "way", "relation", "changeset")
        )
        if (!extended) {
            warning("`object_type` only applies when `extended = TRUE`")
        }
    }

    # build the common bits of the command
    args <- c("fileinfo", input_path)
    if (extended) args <- c(args, "--extended")
    if (crc) args <- c(args, "--crc")
    if (!is.null(get)) args <- c(args, paste0("--get=", get))
    if (verbose) args <- c(args, "--verbose")
    args <- c(args, if (progress) "--progress" else "--no-progress")
    if (!is.null(object_type) && extended) {
        args <- c(args, paste0("--object-type=", object_type))
    }

    # 1) Plain text
    if (output == "text") {
        logs <- processx::run(
            "osmium",
            args,
            echo = echo,
            spinner = spinner,
            echo_cmd = echo_cmd
        )
        # logs$stdout and logs$stderr are captured in memory; nothing is written to disk
        return(logs$stdout)
    }

    # 2) JSON or list: add --json
    args_json <- c(args, "--json")
    logs <- processx::run(
        "osmium",
        args_json,
        echo = echo,
        spinner = spinner,
        echo_cmd = echo_cmd
    )
    raw_json <- logs$stdout

    if (output == "json") {
        return(raw_json)
    }

    # 3) output == "list": parse in-memory via RcppSimdJson::fparse()
    #    (no temp files, no disk writes)
    return(RcppSimdJson::fparse(raw_json))
}
