#' Show information about an OSM file
#'
#' @description
#' This is a wrapper for [osmium fileinfo](https://docs.osmcode.org/osmium/latest/osmium-fileinfo.html).
#' Returns OSM file & header info in three possible formats:
#' - \code{"text"}: the original plain‐text dump
#' - \code{"json"}: the raw JSON string emitted by \code{--json}
#' - \code{"list"}: the JSON parsed to an R list via \code{RcppSimdJson::fparse()}
#'
#' @param input_path String. Path to the OSM file.
#'
#' @param extended      A logical(1). Read the entire file (not just header)? Defaults to `FALSE`. Reading extended info may be slow, as it reads the entire file. This is also required if the file does not have a bounding box in the header, and you need to calculate it from the data. Specifically, to get or calculate the bounding box, you need can use the [osm_get_bbox] function.
#'
#' @param get String or NULL. If non-NULL, returns only this variable's value (using `--get=`). Must be a full CLI variable name (e.g. `file.name`, `header.option.generator`, `data.bbox`, or any other supported variable listed by `osmium fileinfo --show-variables`). A shorthand of `"generator"` is recognized and maps to `header.option.generator`. To get the list of valid variable names, use `osm_file_info_variables()`.
#' @param crc A logical. Calculate CRC32? Defaults to `FALSE`; automatically enabled if `output = "json"`. Ignored when `get` is used.
#' @param object_type Character vector or NULL. Only applies when `extended = TRUE`.
#'   One or more of `"node","way","relation","changeset"`.
#' @param output One of `"text"`, `"json"`, or `"list"`. Defaults to `"text"`.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by the function call to the screen.
#'   Defaults to `FALSE`.
#' @param echo A logical. Whether to print the standard output and error generated by the Osmium call to the screen.
#'   Defaults to `TRUE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the Osmium call is being executed.
#'   Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the running command. Defaults to `FALSE`.
#' @param progress A logical. Whether to display a progress bar while running
#'   the command. Defaults to `FALSE`.
#'
#' @return
#' - If `output = "text"`: character scalar (plain-text dump).
#' - If `output = "json"`: character scalar (raw JSON string).
#' - If `output = "list"`: an R list parsed via `RcppSimdJson::fparse()`.
#' - If `get` is non-NULL: a single string `"<var>=<value>"`.
#'
#'
#' @examplesIf identical(tolower(Sys.getenv("NOT_CRAN")), "true")
#' pbf <- system.file("extdata/cur.osm.pbf", package = "rosmium")
#'
#' # 1. plain-text (default)
#' txt <- osm_file_info(pbf)
#' cat(substr(txt, 1, 200), "...", "\n")
#'
#' # 2. raw JSON
#' j <- osm_file_info(pbf, output = "json")
#' cat(substr(j, 1, 200), "...", "\n")
#'
#' # 3. parsed list
#' lst <- osm_file_info(pbf, output = "list")
#' str(lst[c("file","header")])
#'
#' @export
osm_file_info <- function(
    input_path,
    extended = FALSE,
    get = NULL,
    crc = FALSE,
    object_type = NULL,
    output = c("text", "json", "list"),
    echo_cmd = FALSE,
    echo = FALSE,
    spinner = TRUE,
    verbose = FALSE,
    progress = FALSE
) {
    # Preconditions
    assert_osmium_is_installed()
    checkmate::assert_file_exists(input_path)
    checkmate::assert_logical(extended, any.missing = FALSE, len = 1)
    checkmate::assert_logical(crc, any.missing = FALSE, len = 1)
    checkmate::assert_logical(echo_cmd, any.missing = FALSE, len = 1)
    checkmate::assert_logical(spinner, any.missing = FALSE, len = 1)
    checkmate::assert_logical(verbose, any.missing = FALSE, len = 1)
    checkmate::assert_logical(progress, any.missing = FALSE, len = 1)

    output <- match.arg(output)

    # Auto-enable CRC for JSON
    if (output == "json") crc <- TRUE

    # Handle get
    if (!is.null(get)) {
        checkmate::assert_string(get)
        vars <- .get_osm_fileinfo_variables(
            echo = echo,
            spinner = spinner,
            echo_cmd = echo_cmd
        )
        # full name?
        if (grepl("\\.", get)) {
            if (!(get %in% vars)) {
                stop(sprintf(
                    "Unknown variable '%s'; run `osm_file_info_variables()` to see valid names.",
                    get
                ))
            }
            get_full <- get
        } else {
            # final-component match
            endings <- sub(".*\\.", "", vars)
            matches <- vars[endings == get]
            if (length(matches) == 1) {
                get_full <- matches
            } else if (length(matches) > 1) {
                stop(sprintf(
                    "Ambiguous shorthand '%s'; matches: %s",
                    get,
                    paste(matches, collapse = ", ")
                ))
            } else {
                stop(sprintf(
                    "Unknown shorthand '%s'; run `osm_file_info_variables()` to discover valid names.",
                    get
                ))
            }
        }
        logs <- processx::run(
            "osmium",
            c("fileinfo", input_path, paste0("--get=", get_full)),
            echo = echo,
            spinner = spinner,
            echo_cmd = echo_cmd
        )
        val <- trimws(logs$stdout)
        return(paste0(get, "=", val))
    }

    # Validate object_type
    if (!is.null(object_type)) {
        checkmate::assert_subset(
            object_type,
            c("node", "way", "relation", "changeset")
        )
        if (!extended)
            warning("`object_type` only applies when `extended = TRUE`.")
    }

    # Build base args
    args <- c("fileinfo", input_path)
    if (extended) args <- c(args, "--extended")
    if (crc) args <- c(args, "--crc")
    if (verbose) args <- c(args, "--verbose")
    args <- c(args, if (progress) "--progress" else "--no-progress")
    if (!is.null(object_type) && extended)
        args <- c(args, paste0("--object-type=", object_type))

    # Dispatch
    if (output == "text") {
        logs <- processx::run(
            "osmium",
            args,
            echo = echo,
            spinner = spinner,
            echo_cmd = echo_cmd
        )
        return(logs$stdout)
    }

    logs <- processx::run(
        "osmium",
        c(args, "--json"),
        echo = echo,
        spinner = spinner,
        echo_cmd = echo_cmd
    )
    raw_json <- logs$stdout
    if (output == "json") return(raw_json)
    return(RcppSimdJson::fparse(raw_json))
}

#' List available variables for osm_file_info
#'
#' @description
#' Fetches the set of valid variable names supported by the underlying Osmium CLI.
#'
#' @inheritParams osm_file_info
#' @return Character vector of variable names.
#'
#' @examplesIf identical(tolower(Sys.getenv("NOT_CRAN")), "true")
#' vars <- osm_file_info_variables()
#' head(vars)
#'
#' @export
osm_file_info_variables <- function(
    echo_cmd = FALSE,
    spinner = TRUE,
    echo = FALSE
) {
    # Delegates to internal cache-aware fetcher
    .get_osm_fileinfo_variables(
        echo = echo,
        spinner = spinner,
        echo_cmd = echo_cmd
    )
}

# internal cache for variable names
.osm_fileinfo_cache <- new.env(parent = emptyenv())
.get_osm_fileinfo_variables <- function(
    echo = FALSE,
    spinner = FALSE,
    echo_cmd = FALSE
) {
    if (is.null(.osm_fileinfo_cache$vars)) {
        logs <- processx::run(
            "osmium",
            c("fileinfo", "--show-variables"),
            echo = echo,
            spinner = spinner,
            echo_cmd = echo_cmd
        )
        vars <- strsplit(logs$stdout, "\r?\n")[[1]]
        vars <- trimws(vars)
        .osm_fileinfo_cache$vars <- vars[nzchar(vars)]
    }
    .osm_fileinfo_cache$vars
}
