#' Merge several sorted OSM files
#'
#' This is a wrapper for [osmium merge](https://docs.osmcode.org/osmium/latest/osmium-merge.html).
#' Merges multiple sorted OSM files into a single output, removing duplicate objects.
#'
#' @param input_paths Character vector of paths to one or more existing, sorted OSM files.
#' @param output_path String. Path to the file where the merged result will be written.
#' @param with_history A logical. If `TRUE`, suppress warnings about multiple versions
#'   of the same object. Defaults to `FALSE`.
#' @param input_format Optional string. Force input format (e.g. `"osm"`, `"pbf"`). If `NULL`, autodetect.
#' @param output_format Optional string. Force output format (e.g. `"osm"`, `"pbf"`). If `NULL`, autodetect.
#' @param fsync A logical. If `TRUE`, call `fsync` after writing to force flushing buffers. Defaults to `FALSE`.
#' @param generator Optional string. Name/version for the `generator` header. Defaults to Osmium’s own.
#' @param overwrite A logical. If `TRUE`, allow overwriting an existing `output_path`. Defaults to `FALSE`.
#' @param output_header Named character vector of additional header options. Each name is the header key,
#'   each value is the header value. A zero‐length value (`""`) writes `OPTION!`. Defaults to `NULL`.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by the function call to the screen.
#'   Defaults to `FALSE`.
#' @param echo A logical. Whether to print the standard output and error generated by the Osmium call to the screen.
#'   Defaults to `TRUE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the Osmium call is being executed.
#'   Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the running command. Defaults to `FALSE`.
#' @param progress A logical. Whether to display a progress bar while running
#'   the command. Defaults to `FALSE`.
#'
#' @return Invisibly returns the normalized path to `output_path`.
#'
#' @export
osm_merge <- function(
  input_paths,
  output_path,
  with_history = FALSE,
  input_format = NULL,
  output_format = NULL,
  fsync = FALSE,
  generator = NULL,
  overwrite = FALSE,
  output_header = NULL,
  echo_cmd = FALSE,
  echo = TRUE,
  spinner = TRUE,
  verbose = FALSE,
  progress = FALSE
) {
  assert_osmium_is_installed()

  ## Validate inputs
  checkmate::assert_character(input_paths, any.missing = FALSE, min.len = 1)
  for (p in input_paths) {
    checkmate::assert_file_exists(p, access = "r")
  }
  checkmate::assert_string(output_path)

  checkmate::assert_logical(with_history, len = 1)
  if (!is.null(input_format)) checkmate::assert_string(input_format)
  if (!is.null(output_format)) checkmate::assert_string(output_format)
  checkmate::assert_logical(fsync, len = 1)
  if (!is.null(generator)) checkmate::assert_string(generator)
  checkmate::assert_logical(overwrite, len = 1)
  if (!is.null(output_header)) {
    checkmate::assert_named(output_header, type = "unique")
    checkmate::assert_character(output_header)
  }
  checkmate::assert_logical(echo_cmd, len = 1)
  checkmate::assert_logical(echo, len = 1)
  checkmate::assert_logical(spinner, len = 1)
  checkmate::assert_logical(verbose, len = 1)
  checkmate::assert_logical(progress, len = 1)

  ## Build flags
  hist_flag <- if (with_history) "--with-history" else character()
  input_fmt_flag <- if (!is.null(input_format))
    paste0("--input-format=", input_format) else character()
  output_fmt_flag <- if (!is.null(output_format))
    paste0("--output-format=", output_format) else character()
  fsync_flag <- if (fsync) "--fsync" else character()
  gen_flag <- if (!is.null(generator)) paste0("--generator=", generator) else
    character()
  overwrite_flag <- if (overwrite) "--overwrite" else character()
  header_flags <- if (!is.null(output_header)) {
    unname(vapply(
      names(output_header),
      function(nm) {
        val <- output_header[[nm]]
        hdr <- if (nzchar(val)) paste0(nm, "=", val) else paste0(nm, "!")
        paste0("--output-header=", hdr)
      },
      character(1)
    ))
  } else character()
  verbose_flag <- if (verbose) "--verbose" else character()
  progress_flag <- if (progress) "--progress" else "--no-progress"
  output_flag <- paste0("--output=", output_path)

  ## Assemble and run
  args <- c(
    "merge",
    input_paths,
    hist_flag,
    input_fmt_flag,
    output_fmt_flag,
    fsync_flag,
    gen_flag,
    output_flag,
    overwrite_flag,
    header_flags,
    verbose_flag,
    progress_flag
  )
  processx::run(
    "osmium",
    args,
    echo = echo,
    spinner = spinner,
    echo_cmd = echo_cmd
  )

  invisible(normalizePath(output_path))
}
