#' Sort OSM files
#'
#' This is a wrapper for [osmium sort](https://docs.osmcode.org/osmium/latest/osmium-sort.html). Combines and sorts the content of one or more OSM files.  Objects are ordered by type (node, way, relation), by ID (negative IDs first, then positive, sorted by absolute value), and by version.  Duplicate objects are preserved.  Works with data, history, and change files.
#'
#' @param input_paths Character vector of paths to one or more existing OSM files.
#' @param output_path String. Path to the file where the sorted output will be written.
#'   The format is inferred from the extension unless \code{output_format} is set.
#' @param strategy Character(1). Sorting strategy, either \code{"simple"} (default,
#'   single-pass in-memory) or \code{"multipass"} (three passes, lower memory).
#' @param input_format Optional string. Force the input format (e.g. \code{"osm"},
#'   \code{"pbf"}, \code{"osc"}).  If \code{NULL}, autodetect.
#' @param output_format Optional string. Force the output format (e.g. \code{"osm"},
#'   \code{"pbf"}, \code{"osc"}).  If \code{NULL}, autodetect.
#' @param fsync Logical(1). If \code{TRUE}, call \code{fsync} after writing the
#'   output file to flush buffers.  Defaults to \code{FALSE}.
#' @param generator Optional string.  Name/version to write into the \code{generator}
#'   header.  Default is \code{"osmium/<version>"}.
#' @param overwrite Logical(1). If \code{TRUE}, allow overwriting an existing
#'   \code{output_path}.  Defaults to \code{FALSE}.
#' @param output_header Named character vector of additional header options.
#'   Each name is the header key, each value is the header value.  If a value
#'   is \code{""}, writes \code{OPTION!}.  Defaults to \code{NULL}.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by the function call to the screen.
#'   Defaults to `FALSE`.
#' @param echo A logical. Whether to print the standard output and error generated by the Osmium call to the screen.
#'   Defaults to `TRUE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the Osmium call is being executed.
#'   Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the running command. Defaults to `FALSE`.
#' @param progress A logical. Whether to display a progress bar while running
#'   the command. Defaults to `FALSE`.
#'
#' @return Invisibly returns the normalized path to \code{output_path}.
#'
#' @examplesIf identical(tolower(Sys.getenv("NOT_CRAN")), "true")
#' # sort a single PBF file
#' pbf <- system.file("extdata/cur.osm.pbf", package = "rosmium")
#' out <- tempfile(fileext = ".osm.pbf")
#' osm_sort(pbf, out, overwrite = TRUE)
#'
#' @export
osm_sort <- function(
  input_paths,
  output_path,
  strategy = c("simple", "multipass"),
  input_format = NULL,
  output_format = NULL,
  fsync = FALSE,
  generator = NULL,
  overwrite = FALSE,
  output_header = NULL,
  echo_cmd = FALSE,
  echo = TRUE,
  spinner = TRUE,
  verbose = FALSE,
  progress = FALSE
) {
  assert_osmium_is_installed()

  # validate inputs
  checkmate::assert_character(input_paths, any.missing = FALSE, min.len = 1)
  for (p in input_paths) {
    checkmate::assert_file_exists(p, access = "r")
  }
  checkmate::assert_string(output_path)
  strategy <- match.arg(strategy)
  if (!is.null(input_format)) checkmate::assert_string(input_format)
  if (!is.null(output_format)) checkmate::assert_string(output_format)
  checkmate::assert_logical(fsync, len = 1, any.missing = FALSE)
  if (!is.null(generator)) checkmate::assert_string(generator)
  checkmate::assert_logical(overwrite, len = 1, any.missing = FALSE)
  if (!is.null(output_header)) {
    checkmate::assert_named(output_header, type = "unique")
    checkmate::assert_character(output_header)
  }
  checkmate::assert_logical(echo_cmd, len = 1, any.missing = FALSE)
  checkmate::assert_logical(echo, len = 1, any.missing = FALSE)
  checkmate::assert_logical(spinner, len = 1, any.missing = FALSE)
  checkmate::assert_logical(verbose, len = 1, any.missing = FALSE)
  checkmate::assert_logical(progress, len = 1, any.missing = FALSE)

  # check output path
  assert_output_path_multi_ext(output_path, overwrite)

  # build flags
  strat_flag <- paste0("--strategy=", strategy)
  input_flag <- if (!is.null(input_format))
    paste0("--input-format=", input_format) else character()
  output_fmt_flag <- if (!is.null(output_format))
    paste0("--output-format=", output_format) else character()
  fsync_flag <- if (fsync) "--fsync" else character()
  gen_flag <- if (!is.null(generator)) paste0("--generator=", generator) else
    character()
  overwrite_flag <- if (overwrite) "--overwrite" else character()
  header_flags <- if (!is.null(output_header)) {
    unname(vapply(
      names(output_header),
      function(nm) {
        val <- output_header[[nm]]
        hdr <- if (nzchar(val)) paste0(nm, "=", val) else paste0(nm, "!")
        paste0("--output-header=", hdr)
      },
      character(1)
    ))
  } else character()
  verbose_flag <- if (verbose) "--verbose" else character()
  progress_flag <- if (progress) "--progress" else "--no-progress"
  output_flag <- paste0("--output=", output_path)

  # assemble args
  args <- c(
    "sort",
    input_paths,
    strat_flag,
    input_flag,
    output_fmt_flag,
    fsync_flag,
    gen_flag,
    output_flag,
    overwrite_flag,
    header_flags,
    verbose_flag,
    progress_flag
  )

  # run osmium sort
  processx::run(
    "osmium",
    args,
    echo = echo,
    spinner = spinner,
    echo_cmd = echo_cmd
  )

  invisible(normalizePath(output_path))
}
