on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: check

jobs:
  check:
    # shell needs to use login mode so conda env activation can work
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-latest, r: 'release'}
        - {os: macOS-latest, r: 'release'}
        - {os: ubuntu-22.04, r: 'devel'}
        - {os: ubuntu-22.04, r: 'release'}
        - {os: ubuntu-22.04, r: 'oldrel'}

    env:
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          activate-environment: my-env

      - name: Update PATH env variable to include conda bin dir (Linux and MacOS)
        run: echo "PATH=$PATH" >> $GITHUB_ENV
        if: runner.os != 'Windows'

      - name: Install osmium
        run: conda install -c conda-forge osmium-tool=1.16.0

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
